spring.datasource.url=jdbc:mysql://localhost:3307/RideRecordDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
item.page-size=15

spring.kafka.bootstrap-servers=RideReq_messages:9092
